apiVersion: v1
kind: Config
current-context: garden-kyma--c-5d3089e-external
clusters:
  - name: garden-kyma--c-5d3089e-external
    cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQWsrZ0F3SUJBZ0lSQUpVWnhxTDZTMVB5bjN1alVNdnd4V1F3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpRd05EQTBNVE16T0RBeldoY05NelF3TkRBME1UTXpPREF6V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBTmJQCkprZUcvcDhpczZCSVo4dnNpdk1vOWJUazk5cWZLTzRHUGVnc29FN0JHUXFpK0VTV25pT2tXSy8xQXpETDF6YzgKc0dmNnpQU2k2K2FvY2lhK0xDeUxPenVXQUNpdkZmUGEwaWliK2ZvSWJrZURrVzcybTgwTXBPb1NuSGE1aG5kOQpOZ3NDQkpoQnhDclFwY1FYZEFiSEpidU5LNWxaZEE1aGQ1R1E3YzRjZGZmVE05cUllV24rK3lVdTl5dFdjdlVJCjBRQ3lRdDhWUUJSdHFXeUpKOTdtSTNscWJJNHBkVDl5TDY4WjU0elh6a1ZCNmUyM08xYkJxZVFVQnMySXNYVXkKYlRHZnlEVW1oMklBaHpzU2NVV3h2RDZRTENubHJiL0NUYzAwL3BlZi81K083bUVJbFpVeTdVZEtiZjIrUWVWYwpUTkUrM0MybmJnUk5zTlc3MmxON294TFJEYzFzdVpGNTI5RGh1REwxdk82MXJMcjZqdzZHQVJERjV5THNyekdVCkppNkdyNjNoRkxqVmxPNG8xeHRoN3Ewdy9Va1ovYTl0VmlxbHo3YmFyaUxzK2U1OEk2NmN4NWsrOTRtN2FDNHQKaktEZllNck5JdDNRVTJJdmkzSzFQZXBhbVRabDNkUXgwVEFEU1FnNFFvVmoxL3pBWGhndHcrSkNoUHJPblFJRApBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVYTkprSHoyN0xDRUZGMEZSVWFpdEswLzgxeW93RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQUlYakFNamIKR2w2OVR1MDgrK0t3NzZUQmpRZmR1Zk95Z3VDdmJuc3JwYjRiK3dZcHpOanlOVll1S053Zy84NTB0TXMyOHZhNQpPMk5mc1laZkgvT2F2SktvYjd0cHg1MXhzdEdTNTlNQ3c5YXJoa0k2ejFtSjJydlFXbzJEMDhqTGVDOHVTellvCkhEK3psKzRqN2NTZ3pGQnhyVzJ5VjF2UFlGM29HRFQ3VTRyM0Q4cmUwNUNIOFBwenRXSTg1SlUxeXN6blB0bysKUE9ZUXhERDFtY28zY0NvcVJRWFdWOHRqY0g4R3R2UEI0R05NNVN2ZWsyV0pMVjAwT2xqS3QranhRU1g5d1crZQpYTGdqcVpNM2QxK2dFdFFWd2JnV05Idm5WNHEwMTYvM2svVFpjS09yaG9VOVY0ODBpUUFsRVRWbHBITXAyTVV5CkFreEU1YU04OXJjakpXQzJwMjJELzdjQUx1c1JLREpSV1FYeDdnSmxWSnpTQ21uYWhsS0w1djNINDJIMisyOFMKc01GbWpTaGFDbDB3UytnM25nK3VIRk5IUy9UWGJWN1Q5QStaaGUzeUpEaUtZTHN6Y2hXVVZyc2ZPcnFyM2dSQwpyb0phUERackdWNFkyU3FCQlFVYUdvSXFxUzlwQU5JcEdpWStQdERxalNKSjNXT29aLytMaVNmcnB3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://api.c-5d3089e.kyma.ondemand.com
contexts:
  - name: garden-kyma--c-5d3089e-external
    context:
      cluster: garden-kyma--c-5d3089e-external
      user: garden-kyma--c-5d3089e-external
users:
  - name: garden-kyma--c-5d3089e-external
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - '--oidc-issuer-url=https://kyma.accounts.ondemand.com'
          - '--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6'
          - '--oidc-extra-scope=email'
          - '--oidc-extra-scope=openid'
        command: kubectl-oidc_login
        installHint: |
          kubelogin plugin is required to proceed with authentication
          # Homebrew (macOS and Linux)
          brew install int128/kubelogin/kubelogin

          # Krew (macOS, Linux, Windows and ARM)
          kubectl krew install oidc-login

          # Chocolatey (Windows)
          choco install kubelogin
